version: '3.8'

services:

  api:
    image: tomfumb/bvsar-feature-extract-api
    ports:
      - 8023:80
    environment:
      GDAL_CONFIG_FILE: /app/feature_extract/gdal-local.ini=value
      data_access_prefix: /vsis3/bvsar
    command: uvicorn feature_extract_api.app:app --host 0.0.0.0 --port 80 --reload

  minio:
    ports:
      - 9000:9000