version: '3.8'

services:

  minio:
    image: minio/minio
    env_file:
      - ./minio/.env.creds
    command: server /data
    healthcheck:
      test: curl -s http://localhost:9000 > /dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 5s
      timeout: 1s
      retries: 10
    ports:
      - 9001:9000

  minio-client:
    build:
      context: ./minio/client
    env_file:
      - ./minio/.env.creds
    environment:
      MINIO_URL: http://minio:9000
    depends_on:
      minio:
        condition: service_healthy

  aws-cli:
    image: amazon/aws-cli:2.4.22
    env_file:
      - ./minio/.env.creds
    volumes:
      - ./feature_extract/data:/data
    depends_on:
      minio-client:
        condition: service_completed_successfully
    entrypoint: ""
    command: sh -c "echo Uploading FileGeobuf data to minio...; ls -1 /data/*.fgb | xargs -I {} aws --endpoint-url http://minio:9000 s3 cp {} s3://bvsar"

  api:
    image: tomfumb/bvsar-feature-extract-api
    ports:
      - 8023:80
    env_file:
      - ./minio/.env.creds
    environment:
      # GDAL / FlatGeobuf config
      AWS_S3_ENDPOINT: minio:9000
      AWS_HTTPS: "NO"
      AWS_VIRTUAL_HOSTING: "FALSE"
      # API config
      data_access_prefix: /vsis3/bvsar
    command: uvicorn feature_extract_api.app:app --host 0.0.0.0 --port 80 --reload
    depends_on:
      aws-cli:
        condition: service_completed_successfully
