version: '3.8'

services:

  api:
    build:
      args:
        PIP_INSTALL_ARG: "[test]"
    image: tomfumb/bvsar-feature-extract-api-test
    environment:
      data_access_prefix: /app/feature_extract/tests/data